export const PUSH_CONTENTFUL_DATA = "PUSH_CONTENTFUL_DATA";
export const PUSH_FEATURED_DATA = "PUSH_FEATURED_DATA";
export const CONTENTFUL_ERROR = "CONTENTFUL_ERROR";
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
